//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: agnmodel
// Function header: agnmodelFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createagnmodelFunctionMap();

extern "C"  {


	xsf77Call    agnsed_;
}


#endif
