//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: agnmodel
// Function body: agnmodelFunctionMap.cxx

#include    "agnmodelFunctionMap.h"

#include    <XSModelFunction.h>

void 
createagnmodelFunctionMap()
{


	XSFunctionMap["agnsed"]   = new XSCall<xsf77Call>(agnsed_);

}
