//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: agnmodel Created :
// Initializer: agnmodel.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "agnmodelFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Agnmodel_Init(Tcl_Interp* tclInterp);
extern "C" int Agnmodel_SafeInit(Tcl_Interp* tclInterp);

int Agnmodel_Init(Tcl_Interp* tclInterp)
{
        return Agnmodel_SafeInit(tclInterp);
}

int Agnmodel_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "agnmodel";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createagnmodelFunctionMap();
        XSModelFunction::updateComponentList
              ("/home/raad/PhD/Dropbox/Code/AGN_togithub/agnsed_local_model/lmodel_agnsed.dat");
        return TCL_OK;

}

